# Generated by Django 4.2.1 on 2023-05-28 12:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('worked', models.IntegerField(blank=True, default=0, null=True)),
                ('broke', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 5, 28, 12, 6, 4, 425020, tzinfo=datetime.timezone.utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2023, 5, 28, 12, 6, 4, 425020, tzinfo=datetime.timezone.utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
    ]
