# Generated by Django 4.2.1 on 2023-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_graph_deviceinformation_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yangi', models.IntegerField(blank=True, default=0, null=True)),
                ('tamirlandi', models.IntegerField(blank=True, default=0, null=True)),
                ('broken', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
